### ISSUE TITLE
Assembly resolving failed:

### ISSUE THREAD

**Issue by mattman73** [krishKM/VBA_TOOLS#2]
Hi 
I'm getting this error and I'm not sure why please can you help.
Assembly resolving failed:
VBA_TOOLS is requesting for: Newtonsoft.json 
error: String cannot have zreo length.
this error in on a windows 7 Pro SP1 pc
but the code is working on a windows 10 laptop.

**Comment by krishKM** [comment]
Can you add what you tried to do so we can try to replicate the issue?

**Comment by mattman73** [comment]
using the drag and drop box in excel version 2016

**Comment by mattman73** [comment]
I have just tried to use the DialogRich code and got this error on the same PC and the other errors.
Run-Time error '-2147024894 (80070002): Could not load file or assembly 'Nestonsoft.json, Version-11.0.0.0, Cultrue=neutral,PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified

**Comment by krishKM** [comment]
I assume the bin folder is missing. The bin folder has those dlls in it. try to copy the bin folder where the vba_tools.dll is.

**Comment by mattman73** [comment]
it was running across a mapped network drive and I believe that is what was causing the issue, many thanks Matt
