### ISSUE TITLE
Last Update not working

### ISSUE THREAD

**Issue by lajjutz** [krishKM/VBA_TOOLS#53]
Hello Krish

Glad you appear again, hope you are doing well also...
I downloaded the recent update, but look like something is not good. Could you check..

Thanks again for your time for this project.

![image](https://user-images.githubusercontent.com/44538069/151563117-5f4e1657-7bd4-40ab-b09c-b7ef10f63c07.png)

**Comment by krishKM** [comment]
Hi Lajjutz, thank you.
Can you add few more info & step-by-step so I can try to reproduce on my side.
Please also mention if you are using 32bit or 64bit office.

**Comment by lajjutz** [comment]
Hello

My mistake, The computer I tested was x86, all good..

![image](https://user-images.githubusercontent.com/44538069/151591413-4363b86a-5c60-400f-8b25-ed4cbfa1981a.png)
